name: Enforce Merge Policy

on:
  pull_request:
    branches:
      - qa

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          if [[ ${{ github.event.pull_request.base.ref }} != "develop" ]]; then
            echo "Pull requests to qa must come from develop"
            exit 1
          fi
